seed: 42

# wandb configuration
wandb:
  use: true
  entity: null
  project: ibl-video

# Logging directories
dirs:
  checkpoint_dir: checkpoints  # save model state dicts (todo optimizer states)
  log_dir: /expanse/lustre/scratch/ywang74/temp_project/video-spike/results  # save tensorboard logs
  data_dir: /expanse/lustre/scratch/ywang74/temp_project/Downloads/ibl-video
  


# Training configuration
training:
  num_epochs: 100
  train_batch_size: 16
  test_batch_size: 16  
  shuffle_test_dataloader: false    # Shuffle test dataloader between epochs
  num_workers: 1 # Number of workers for the DataLoader

  save_plot_every_n_epochs: 20  # Plot the model output every n epochs
  save_every: 100  # Save checkpoint
  eval_every: null  # Eval model

  use_mtm: false
  mask_type: embd # embd/input
  mask_mode: ["temporal"]

# Model configuration. 
# Will be passed to the model __init__  method if a model is not passed to the Trainer __init__ method.
model: 
  model_class: null   # Any registered model class name. 

# Data configuration.
data:
  modalities: 
    ap: 
      transform: null
      transform_kwargs: {}
      input: False
    video: 
      transform: null
      transform_kwargs: {'ToTensor','Reshape'}
      width: 128
      height: 128
      input: False
    choice: 
      transform: null
      transform_kwargs: {}
      input: False
    block: 
      transform: null
      transform_kwargs: {}
      input: False
    wheel-speed: 
      transform: null
      transform_kwargs: {}
      input: False
    whisker-motion-energy: 
      transform: null
      transform_kwargs: {}
      input: False
    whisker-of: 
      transform: null
      transform_kwargs: {}
      input: True
    of: 
      transform: null
      transform_kwargs: {}
      input: False

  # dataset_name: lorenz # Any registered dataset name.
  dataset_name: ibl # Any registered dataset name.
  dataset_class: ssl # Any registered dataset class name.

  # Load raw dataset if a dataset is not passed to the Trainer __init__ method. 
  hf_dataset_name: null   # from huggingface
  json_dataset_name: null # from json file

  train_name: train   # name of the train split in the raw datasete
  test_name: test     # name of the test split in the raw datasete
  train_len: null     # used length of the train dataset. null to use all
  test_len: null      # used length of the test dataset. null to use all

  LOG_EPSILON: 1.e-7 # epsilon for log transformation, to prevent log(0)
  use_lograte: True # use lograte

  max_time_length: 100    # max_time_length has to be a multiple of time patch size
  max_space_length: 668   # max_space_length has to be a multiple of space patch size
  patching: true # patching the neurons
  sort_by_depth: false
  sort_by_region: false
  brain_region: all
  spike_augmentation: false

  include_behav: false # include behavior data
  target: whisker-motion-energy # target behavior

  load_meta: true

  num_sessions: 3
  test_session_eid: ["671c7ea7-6726-4fbe-adeb-f89c2c8e489b"] 

  split_method: session_based # random_split/session_based

  use_aligned_test: False

# Method configuration. Contains kwargs that are specific to the training method.
method:

  # Passed to the model __init__ method together with the model config
  model_kwargs: 
    method_name: ssl #ssl 

    use_lograte: true
    loss: poisson_nll  # poisson_nll # mse/other distirbutions (todo)
    output_size: 2
    clf: false
    reg: false

  # Passed to the Dataset __init__ method together with the raw dataset. 
  dataset_kwargs: {}

  # Passed to the DataLoader __init__ method.
  dataloader_kwargs:
    # Contains which keys to pad, along which dimension with which value
    pad_dict: 
      spikes:
          dim: 0
          side: right
          value: 0
          truncate: null
          min_length: null
      

optimizer:
  gradient_accumulation_steps: 1
  lr: 5.e-5
  wd: 0.01
  eps: 1.e-8
  warmup_pct: 0.15 # cosine/linear
  gamma: 0.95     # step
  div_factor: 10  # cosine
  scheduler: cosine # step/cosine/linear