model_class: VideoMAE

image_size: 224
patch_size: 16
num_channels: 3
num_frames: 16
tubelet_size: 2
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 3072
hidden_act: "gelu"
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0
initializer_range: 0.02
layer_norm_eps: 1e-12
qkv_bias: True
use_mean_pooling: True
decoder_num_attention_heads: 6
decoder_hidden_size: 384
decoder_num_hidden_layers: 4
decoder_intermediate_size: 1536
norm_pix_loss: True